### ISSUE TITLE
Issues with deploy script

### ISSUE THREAD

**Issue by valstu** [3stacks/github-actions-react-s3#2]
First of all thanks for the tutorial, it was great! 

I found few bugs in `scripts/deploy.js` file that prevented me from deploying my project to S3:
`const s3 = new AWS.S3();` was declared before `AWS.config()` which lead to following error:
`Error: The AWS Access Key Id you provided does not exist in our records.`

Another one was that on the deploy script you uploaded the `./public` folder but that probably should be `./build` folder, at least when using `create-react-app`.

**Comment by 3stacks** [comment]
Thank you for the issue and for the PR! Closing this one as resolved.
